### ISSUE TITLE
Rating argument doesn't work properly

### ISSUE THREAD

**Issue by prashasth-nair** [Nekos-API/Nekos-API#11]
Sometimes when i select rating for safe, Explicit content are displayed.

**Comment by Nekidev** [comment]
Hello! That is weird, I'll check it out. They're probably incorrectly tagged images.

**Comment by Nekidev** [comment]
Thank you for the report, I also got an explicit image tagged as safe. I'll add an `/images/:id/report` endpoint for this.

**Comment by Nekidev** [comment]
I've added the [`/images/:id/report`](https://nekosapi.com/docs/images/report) endpoint. If you find any image with incorrect information, you can report it with this endpoint.
