### ISSUE TITLE
✘ [ERROR] Could not resolve "../base"

### ISSUE THREAD

**Issue by FluffyRudy** [Nekos-API/Nekos-API#15]
import { NekosAPI } from "nekosapi";
import { useState } from "react";
import "./App.css";

function App() {
  console.log("as");
  return <>hi</>;
}

export default App;

when i run dev server it gives 
`✘ [ERROR] Could not resolve "../base"`

**Comment by Nekidev** [comment]
Hello! (sorry for the delay). This issue goes in [this repository](https://github.com/cataclym/nekosapi). If you're still having this issue you can report it there.
