### ISSUE TITLE
huh?

### ISSUE THREAD

**Issue by Celestemysterios** [Nekos-API/Nekos-API#16]
![Screenshot_20240616-195046.png](https://github.com/Nekos-API/Nekos-API/assets/115356769/f435656e-da4a-4f6c-acf5-091fd602d5b4)

**Comment by Celestemysterios** [comment]
if you said smth in the discord i quitted discord

**Comment by Nekidev** [comment]
this'd go to Nekos-API/Nekos.Land and nekos.land will be up at land.nekosapi.com from now on.
